remote_theme: pmarsceill/just-the-docs
color_scheme: nil
url: "https://allegro.oss.symphony.com"

# Aux links for the upper right navigation
aux_links:
 "Allegro Example Programs":
  - "//examples.allegro.oss.symphony.com"
 "API Source Code":
  - "//github.com/SymphonyOSF/oss-allegro"

search_enabled: true